"""add vacancy status and missed_run_count

Revision ID: 0c23c4fbd068
Revises: a0508fe2360d
Create Date: 2026-08-19 13:25:08.210678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c23c4fbd068'
down_revision: Union[str, Sequence[str], None] = 'a0508fe2360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default set explicitly on both - existing rows (all of them
    # genuinely "active" and with a clean 0 miss streak as of this
    # migration, since mark_missing_vacancies didn't exist before it) need
    # a real value, not NULL, for the NOT NULL columns being added to an
    # already-populated table.
    op.add_column(
        'vacancy',
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='active'),
    )
    op.add_column(
        'vacancy',
        sa.Column('missed_run_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.create_index(op.f('ix_vacancy_status'), 'vacancy', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_status'), table_name='vacancy')
    op.drop_column('vacancy', 'missed_run_count')
    op.drop_column('vacancy', 'status')
    # ### end Alembic commands ###
