"""add generated artifact table

Revision ID: 3553a9417f5a
Revises: 2572d3cb2c8a
Create Date: 2026-08-17 14:37:08.544476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3553a9417f5a'
down_revision: Union[str, Sequence[str], None] = '2572d3cb2c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('vacancy_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacancy_company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacancy_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_artifact_artifact_type'), 'generated_artifact', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_generated_artifact_vacancy_id'), 'generated_artifact', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_artifact_vacancy_id'), table_name='generated_artifact')
    op.drop_index(op.f('ix_generated_artifact_artifact_type'), table_name='generated_artifact')
    op.drop_table('generated_artifact')
    # ### end Alembic commands ###
